### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by barracuda156** [giorgiopapini/netdump#1]
@giorgiopapini Hi, we talked on commandline subreddit now. Here is what builds for me: https://github.com/macos-powerpc/powerpc-ports/commit/54973ac2ae453d90c9d0394dcb0eb915b35b5f82

If makefile changes look sensible to you, I will try re-do it in a way to make it portable.

**Comment by barracuda156** [comment]
Basically, we should set `.so`/`.dylib`, `lib64`/`lib` and appropriate linking flags depending on whether the target system is Darwin or not (i.e. make Darwin a special case, everything else falls back to Linux stuff; I have no idea what *BSD should use, so that is left out).

This gonna compile on Darwin > 15, earlier systems need to rely on `legacy-support` library for `clock_gettime` implementation (it does not exist in macOS before that). It is provided by MacPorts and NetBSD’s pkgsrc.

**Comment by giorgiopapini** [comment]
@barracuda156  Sure, I tried to kinda do that for FreeBSD using this code:
```
ifeq ($(UNAME_S),Linux)
    LIB_PATH := /usr/local/lib64
    RPATH := -Wl,-rpath,\$$ORIGIN:/usr/local/lib64
    INSTALL_LIB_PATH := /usr/local/lib64
    INSTALL_BIN_PATH := /usr/local/bin
endif

ifeq ($(UNAME_S),FreeBSD)
    LIB_PATH := /usr/local/lib
    RPATH := -Wl,-rpath,\$$ORIGIN:/usr/local/lib
    INSTALL_LIB_PATH := /usr/local/lib
    INSTALL_BIN_PATH := /usr/local/bin
endif
```

Apparently FreeBSD make it's not compatible with GNU make. I need to investigate this further, this is just what I’ve found so far, but it might be helpful. If you need more details about the structure of the project and how the different components interact with each other, feel free to ask.

**Comment by barracuda156** [comment]
You can probably use `gmake` on FreeBSD (or OpenBSD/NetBSD). Otherwise `make` is `bsdmake` there.

https://github.com/openbsd/ports/tree/master/devel/gmake

**Comment by giorgiopapini** [comment]
But by doing so, the user would also need to install gmake in order to install netdump, right? bsdmake is built-in instead, correct?

**Comment by barracuda156** [comment]
> But by doing so, the user would also need to install gmake in order to install netdump, right? bsdmake is built-in instead, correct?

Yes, but this is not your headache. If someone adds your app to *BSD ports, they will have to take care of dependencies.
Like MacPorts will need to use `legacysupport` to allow building on earlier macOS.

**Comment by giorgiopapini** [comment]
Oh, alright. Sorry, I'm kind of a newbie when it comes to deploying code. So basically I just have to make sure that the program compiles correctly using gmake on *BSD systems?

**Comment by barracuda156** [comment]
I am not the right person to ask about *BSDs, my experience with them is absolutely minimal. But I think so – this is not a complex project in terms of compilation, there is a single dependency. And AFAIK, using `gmake` for BSD builds is perfectly acceptable.

**Comment by giorgiopapini** [comment]
That's fine. I'm going to try gmake on *BSD systems as soon as possible and see what happens. As for macOS, I honestly don't know anything about it. Thank you for helping me.

**Comment by barracuda156** [comment]
BTW, it should probably declare C11 somewhere, since, I believe, type redefinition is C11 feature. And the code fails to compile with a pre-C11 compiler (gcc-4.2).

**Comment by giorgiopapini** [comment]
What do you mean with type redefinition? Can you point me to some part of the code? Maybe it is something that I can rewrite

**Comment by barracuda156** [comment]
```
protocol.h:36: error: redefinition of typedef ‘protocol_handler’
```

I can rerun the build with gcc-4.2 to make a new log.

**Comment by giorgiopapini** [comment]
Thanks, I will investigate. Type redefinition isn't something I actually considered necessary for the program, maybe it's the result of some bad code I accidentally wrote.

**Comment by giorgiopapini** [comment]
Using gmake, the program compiles without problems. The only bad things that happen are:
- sudo is not installed by default on FreeBSD, so the user should manually switch to the root user to execute the program. It would probably be a good idea to remove the sudo commands from the Makefile and let the user handle the program execution themselves (without having a dedicated make command) instead.
- The ASCII art function doesn't work, probably because the default terminal does not support the needed escape characters.
- The same happens with some keywords like the backslash and arrows.

But it compiles!

![Image](https://github.com/user-attachments/assets/8fe2d5b1-632b-4559-adb9-886f7ade54f8)

**Comment by barracuda156** [comment]
Not sure about FreeBSD, but OpenBSD has `doas`: https://man.openbsd.org/doas

**Comment by barracuda156** [comment]
```
--->  Building netdump
Executing:  cd
"/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/netdump-1.0.0"
&& /usr/bin/make -j6 -w all
CC="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2"
CXX="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cxx/usr/bin/g++-4.2"
OBJC="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/objc/usr/bin/gcc-4.2"
OBJCXX="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/objcxx/usr/bin/g++-4.2"
INSTALL="/usr/bin/install -c"
make: Entering directory
`/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/netdump-1.0.0'
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c utils/protocol.c -o utils/protocol.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c utils/visualizer.c -o utils/visualizer.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c protocols/proto_tables_nums.c -o
protocols/proto_tables_nums.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c command_handler.c -o command_handler.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c custom_dissectors_handler.c -o
custom_dissectors_handler.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/usr/bin/gcc-4.2
-Os -arch ppc -fPIC -g -w -c main.c -o main.o
In file included from utils/custom_dissectors.h:4,
                 from custom_dissectors_handler.h:4,
                 from custom_dissectors_handler.c:1:
utils/protocol.h:36: error: redefinition of typedef ‘protocol_handler’In
file included from protocols/proto_tables_nums.h:4,
                 from protocols/proto_tables_nums.c:1:
protocols/../utils/protocol.h:36: error: redefinition of typedef
‘protocol_handler’

utils/protocol.h:23: error: previous declaration of ‘protocol_handler’ was
hereprotocols/../utils/protocol.h:23: error: previous declaration of
‘protocol_handler’ was here

make: *** [custom_dissectors_handler.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [protocols/proto_tables_nums.o] Error 1
In file included from utils/protocol.c:4:
utils/protocol.h:36: error: redefinition of typedef ‘protocol_handler’
utils/protocol.h:23: error: previous declaration of ‘protocol_handler’ was
here
In file included from utils/../utils/custom_dissectors.h:4,
                 from utils/../command_handler.h:6,
                 from utils/formats.h:6,
                 from command_handler.c:7:
utils/../utils/protocol.h:36: error: redefinition of typedef
‘protocol_handler’
utils/../utils/protocol.h:23: error: previous declaration of
‘protocol_handler’ was here
make: *** [utils/protocol.o] Error 1
In file included from utils/custom_dissectors.h:4,
                 from command_handler.h:6,
                 from main.c:9:
utils/protocol.h:36: error: redefinition of typedef ‘protocol_handler’
utils/protocol.h:23: error: previous declaration of ‘protocol_handler’ was
here
make: *** [command_handler.o] Error 1
make: *** [main.o] Error 1
```

**Comment by giorgiopapini** [comment]
> Not sure about FreeBSD, but OpenBSD has `doas`: https://man.openbsd.org/doas

Yep, FreeBSD also has it, but it isn't built-in. So, it's up to the user to choose whether to install sudo or doas.

**Comment by giorgiopapini** [comment]
I suspect that this snippet of code is causing the redefinition error. Alternatively, there might be issues with the shared library 'libnetdump.so'.

Because here, I’m defining `typedef struct protocol_handler protocol_handler`, and then I define `typedef struct protocol_handler {}` where I add the actual members.
It is inside the `utils/protocol.h` file.

Turns out it was an unnecessary line. I removed it and pushed the changes to the main branch. I honestly don't know why I wrote that line in the first place.

```
typedef enum output_format {
	OUTPUT_FORMAT_NONE = -1,
	OUTPUT_FORMAT_BASIC,
	OUTPUT_FORMAT_RAW,
	OUTPUT_FORMAT_ACII_ART,
} output_format;

typedef enum protocol_layer {
	PROTOCOL_LAYER_NONE = -1,
	PROTOCOL_LAYER_DATALINK,
	PROTOCOL_LAYER_NETWORK,
	PROTOCOL_LAYER_TRANSPORT,
	PROTOCOL_LAYER_APPLICATION
} protocol_layer;

typedef struct protocol_handler protocol_handler;

typedef struct protocol_info {
    int protocol;
    size_t offset;
    int proto_table_num;
} protocol_info;

typedef struct protocol_handler {
    int protocol;
	protocol_layer layer;
    protocol_info (*dissect_proto)(const uint8_t *pkt, uint32_t pkt_len, output_format fmt);
    const char *protocol_name;
} protocol_handler;

typedef struct protocol_handler_mapping {
	protocol_handler *handler;
	int proto_table_num;
} protocol_handler_mapping;
```

**Comment by barracuda156** [comment]
@giorgiopapini It seems there is a regression with 1.0.1, at least I could not build it anymore (1.0.0 builds fine).
I tried with my earlier patch (rebased, of course), without the patch, with gcc14 and gcc-4.2, everything ways this or that way.

Essentially, aside of warning-turned-error in gcc14, there are two failures:
```
make: Entering directory `/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/netdump-1.0.1'
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14 -fPIC -Os -Wno-error=sign-conversion -arch ppc -g -O2 -Werror -Wall -Wextra -Wbad-function-cast -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow -Wstrict-prototypes -Wswitch -Wundef -Wunreachable-code -Wunused-but-set-parameter -Wwrite-strings -Wconversion -Wsign-conversion -c utils/protocol.c -o utils/protocol.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14 -fPIC -Os -Wno-error=sign-conversion -arch ppc -g -O2 -Werror -Wall -Wextra -Wbad-function-cast -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow -Wstrict-prototypes -Wswitch -Wundef -Wunreachable-code -Wunused-but-set-parameter -Wwrite-strings -Wconversion -Wsign-conversion -c utils/visualizer.c -o utils/visualizer.o
utils/visualizer.c: In function '_get_cursor_position':
utils/visualizer.c:60:9: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
   60 |         FD_SET(STDIN_FILENO, &fds);
      |         ^~~~~~
utils/visualizer.c:60:9: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14 -dynamiclib -undefined dynamic_lookup -o libnetdump.dylib utils/protocol.o utils/visualizer.o -fPIC -Wl,-install_name,/opt/local/lib/libnetdump.dylib
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14 -o netdump  -L. -lnetdump -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -arch ppc -lpcap -lm -L. -lnetdump
Undefined symbols for architecture ppc:
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
make: *** [netdump] Error 1
```
```
utils/visualizer.c:60:9: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
   60 |         FD_SET(STDIN_FILENO, &fds);
      |         ^~~~~~
utils/visualizer.c:60:9: warning: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14 -shared -fPIC -o libnetdump.dylib utils/protocol.o utils/visualizer.o
Undefined symbols for architecture ppc:
  "_get_entry", referenced from:
      _get_protocol_handler in protocol.o
  "_raise_error", referenced from:
      __print_raw_pkt in protocol.o
      _create_protocol_handler in protocol.o
      _create_protocol_handler_mapping in protocol.o
      _create_mappings_arr in protocol.o
      _add_mapping in protocol.o
      __print_line in visualizer.o
      _calc_rows in visualizer.o
      ...
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
make: *** [libnetdump.dylib] Error 1
```

And the warning/error is this:
```
utils/visualizer.c: In function '_get_cursor_position':
utils/visualizer.c:60:9: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
   60 |         FD_SET(STDIN_FILENO, &fds);
      |         ^~~~~~
utils/visualizer.c:60:9: error: conversion to 'long unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
cc1: all warnings being treated as errors
make: *** [utils/visualizer.o] Error 1
```
The latter is easy to downgrade back to warring, but I am not sure what got broken with linking now.

**Comment by giorgiopapini** [comment]
Hi @barracuda156! In version 1.0.0, I realized I was using visualizer.o and protocol.o to build both the executable and the shared library. This caused duplicate symbol warnings. I resolved the issue by using these modules only to build the shared library, and then linking the executable against that shared library instead. Maybe that is somehow causing the issue? It's the only change I made to the build process

Is there a way I can reproduce that error on my machine?

**Comment by barracuda156** [comment]
@giorgiopapini It should be reproducible, since I get the same error on Sonoma arm64 (not just on my exotic Snow Leopard on PowerPC):

```
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_net_netdump/netdump/work/compwrap/cc/usr/bin/clang -fPIC -g -O2 -Werror -Wall -Wextra -Wbad-function-cast -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow -Wstrict-prototypes -Wswitch -Wundef -Wunreachable-code -Wunused-but-set-parameter -Wwrite-strings -Wconversion -Wsign-conversion -c utils/protocol.c -o utils/protocol.o
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_net_netdump/netdump/work/compwrap/cc/usr/bin/clang -fPIC -g -O2 -Werror -Wall -Wextra -Wbad-function-cast -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow -Wstrict-prototypes -Wswitch -Wundef -Wunreachable-code -Wunused-but-set-parameter -Wwrite-strings -Wconversion -Wsign-conversion -c utils/visualizer.c -o utils/visualizer.o
/opt/local/var/macports/build/_opt_local_var_macports_sources_macos-powerpc.org_macos-powerpc_PPCPorts_ports_net_netdump/netdump/work/compwrap/cc/usr/bin/clang -shared -fPIC -o libnetdump.so utils/protocol.o utils/visualizer.o
Undefined symbols for architecture arm64:
  "_get_entry", referenced from:
      _get_protocol_handler in protocol.o
  "_raise_error", referenced from:
      __print_raw_pkt in protocol.o
      _create_protocol_handler in protocol.o
      _create_protocol_handler_mapping in protocol.o
      _create_mappings_arr in protocol.o
      _add_mapping in protocol.o
      _add_mapping in protocol.o
      _calc_rows in visualizer.o
      _calc_rows in visualizer.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libnetdump.so] Error 1
```

This is with 0 patching from my end, I commented out old patches and tried to build this as-is.

**Comment by barracuda156** [comment]
P. S. Dynamic lib extension is normally `dylib` in the macOS case, but changing that does not fix the linking error.

**Comment by giorgiopapini** [comment]
Oh maybe I know what's happening. Inside protocol.c and visualizer.c I'm including also other modules (hashmap.c and status_handler.c). Those modules are not included when building the shared library, so maybe that's the reason for the error. I don't know why my machine doesn't tell me that (both in Fedora and in FreeBSD vm)

**Comment by giorgiopapini** [comment]
After digging a bit into this, I suspect that I may have written a function in a place where it shouldn’t really be. I’ll do some code refactoring as soon as I get home. Thanks for pointing this out! I probably wouldn’t have noticed it.

**Comment by giorgiopapini** [comment]
@barracuda156 I wasn’t able to reproduce the error on my machine, but I think I’ve fixed the issue. Would you be able to check it, by any chance? Thanks in advance.

**Comment by barracuda156** [comment]
@giorgiopapini Sure, I will try the build today. Thank you!

**Comment by barracuda156** [comment]
Unfortunately, no change. I still get this error:
```
--->  Building netdump
Executing:  cd
"/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/netdump-bc2a7433458bb869a61489890228e367eaa77561"
&& /usr/bin/make -j6 -w all
CC="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14"
CXX="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cxx/opt/local/bin/g++-mp-14"
OBJC="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/objc/opt/local/bin/gcc-mp-14"
OBJCXX="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/objcxx/opt/local/bin/g++-mp-14"
FC="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/fc/opt/local/bin/gfortran-mp-14"
F77="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/f77/opt/local/bin/gfortran-mp-14"
F90="/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/f90/opt/local/bin/gfortran-mp-14"
INSTALL="/usr/bin/install -c"
make: Entering directory
`/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/netdump-bc2a7433458bb869a61489890228e367eaa77561'
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14
-fPIC -g -O2 -Wall -Wextra -Wbad-function-cast -Wcast-align -Wcast-qual
-Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations
-Wmissing-include-dirs -Wmissing-prototypes -Wnested-externs
-Wpointer-arith -Wredundant-decls -Wsequence-point -Wshadow
-Wstrict-prototypes -Wswitch -Wundef -Wunreachable-code
-Wunused-but-set-parameter -Wwrite-strings -c utils/visualizer.c -o
utils/visualizer.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14
-shared -fPIC -o libnetdump.so utils/protocol.o utils/visualizer.o
/opt/local/var/macports/build/_opt_local_ppcports_net_netdump/netdump/work/compwrap/cc/opt/local/bin/gcc-mp-14
-fPIC -o netdump  -lpcap -lm -L. -lnetdump
-Wl,-rpath,\$ORIGIN:/usr/local/lib64
Undefined symbols for architecture ppc:
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
make: *** [netdump] Error 1
```
P. S. The flag `-Wl,-rpath,\$ORIGIN:/usr/local/lib64` should not be there,
but I just wanted to show the unpatched build. With gcc14 one -Werror
should be dropped due to:
```
utils/visualizer.c:61:9: error: conversion to 'long unsigned int' from
'int' may change the sign of the result [-Werror=sign-conversion]
   61 |         FD_SET((unsigned long)STDIN_FILENO, &fds);
      |         ^~~~~~
utils/visualizer.c:61:9: error: conversion to 'long unsigned int' from
'int' may change the sign of the result [-Werror=sign-conversion]
cc1: all warnings being treated as errors
```
But this is unrelated to linking failure. Probably supplying something
which will contain `main` gonna make the compiler happy, but I wonder why
this stopped working now – on the same set-up the previous version links
fine.

**Comment by giorgiopapini** [comment]
At least it seems I solved the linking error related to "protocol.o" and "visualizer.o". Now it seems like the compiler is not finding the '''int main(void)''' function. I don't now how is it possible since it is clearly defined inside "main.c" file

**Comment by barracuda156** [comment]
@giorgiopapini I will try to fix this now. Usually these errors arise when wrong (from macOS point of view) flags are used.
